---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1v6680ap8xxky5lv0r75403q0ezcuvjcfax3nc4zvvr79pmfq93pqvtrx8t"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1v6680ap8xxky5lv0r75403q0ezcuvjcfax3nc4zvvr79pmfq93pqvtrx8t"
stores:
  yaml:
    indent: 2
